import jsPDF from 'jspdf';
import { StudyNotes } from './studyNotesService';

interface PDFOptions {
  includeHeader?: boolean;
  includeFooter?: boolean;
  colorScheme?: 'blue' | 'purple' | 'green';
}

export const generateStudyGuidePDF = async (
  studyNotes: StudyNotes,
  options: PDFOptions = {}
) => {
  const {
    includeHeader = true,
    includeFooter = true,
    colorScheme = 'blue'
  } = options;

  // Color schemes with proper typing
  type RGB = [number, number, number];
  
  const colorSchemes: Record<string, { primary: RGB; secondary: RGB; accent: RGB }> = {
    blue: { 
      primary: [41, 98, 255], 
      secondary: [59, 130, 246], 
      accent: [147, 197, 253] 
    },
    purple: { 
      primary: [139, 92, 246], 
      secondary: [168, 85, 247], 
      accent: [216, 180, 254] 
    },
    green: { 
      primary: [34, 197, 94], 
      secondary: [74, 222, 128], 
      accent: [187, 247, 208] 
    }
  };

  const theme = colorSchemes[colorScheme];

  // Create PDF
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Helper function to add new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper function to add footer
  const addFooter = (pageNum: number) => {
    if (!includeFooter) return;
    
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${pageNum}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    pdf.text(
      'Generated by Gabrious',
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  };

  // Header Section
  if (includeHeader) {
    // Decorative header bar
    pdf.setFillColor(theme.primary[0], theme.primary[1], theme.primary[2]);
    pdf.rect(0, 0, pageWidth, 40, 'F');

    // Title
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text(studyNotes.title, margin, 15);

    // Subtitle
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${studyNotes.pastor} | ${studyNotes.church}`, margin, 25);
    pdf.text(studyNotes.date, margin, 32);

    yPosition = 50;
  }

  // Format badge
  pdf.setFillColor(theme.accent[0], theme.accent[1], theme.accent[2]);
  pdf.roundedRect(margin, yPosition, 30, 8, 2, 2, 'F');
  pdf.setTextColor(theme.primary[0], theme.primary[1], theme.primary[2]);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.text(studyNotes.format.toUpperCase(), margin + 15, yPosition + 5.5, { align: 'center' });

  // Depth mode badge
  if (studyNotes.depthMode) {
    pdf.roundedRect(margin + 35, yPosition, 35, 8, 2, 2, 'F');
    pdf.text(studyNotes.depthMode.toUpperCase(), margin + 52.5, yPosition + 5.5, { align: 'center' });
  }

  yPosition += 15;

  // Summary Section
  pdf.setFillColor(theme.secondary[0], theme.secondary[1], theme.secondary[2]);
  pdf.rect(margin, yPosition, contentWidth, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('SUMMARY', margin + 3, yPosition + 5.5);
  yPosition += 12;

  pdf.setTextColor(60, 60, 60);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const summaryLines = pdf.splitTextToSize(studyNotes.summary, contentWidth - 6);
  pdf.text(summaryLines, margin + 3, yPosition);
  yPosition += summaryLines.length * 5 + 10;

  checkPageBreak(20);

  // Key Points Section
  pdf.setFillColor(theme.secondary[0], theme.secondary[1], theme.secondary[2]);
  pdf.rect(margin, yPosition, contentWidth, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('KEY POINTS', margin + 3, yPosition + 5.5);
  yPosition += 12;

  studyNotes.keyPoints.forEach((point, index) => {
    checkPageBreak(15);
    
    // Number circle
    pdf.setFillColor(theme.primary[0], theme.primary[1], theme.primary[2]);
    pdf.circle(margin + 4, yPosition + 2, 3, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${index + 1}`, margin + 4, yPosition + 3, { align: 'center' });

    // Point text
    pdf.setTextColor(60, 60, 60);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    const pointLines = pdf.splitTextToSize(point, contentWidth - 15);
    pdf.text(pointLines, margin + 10, yPosition + 3);
    yPosition += pointLines.length * 5 + 5;
  });

  yPosition += 5;
  checkPageBreak(20);

  // Scripture References Section
  pdf.setFillColor(theme.secondary[0], theme.secondary[1], theme.secondary[2]);
  pdf.rect(margin, yPosition, contentWidth, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('SCRIPTURE REFERENCES', margin + 3, yPosition + 5.5);
  yPosition += 12;

  studyNotes.scriptures.forEach((scripture) => {
    checkPageBreak(20);

    // Reference
    pdf.setTextColor(theme.primary[0], theme.primary[1], theme.primary[2]);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text(scripture.reference, margin + 3, yPosition);
    yPosition += 6;

    // Text
    pdf.setTextColor(60, 60, 60);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'italic');
    const scriptureLines = pdf.splitTextToSize(`"${scripture.text}"`, contentWidth - 10);
    pdf.text(scriptureLines, margin + 6, yPosition);
    yPosition += scriptureLines.length * 5 + 8;
  });

  checkPageBreak(20);

  // Discussion Questions Section
  pdf.setFillColor(theme.secondary[0], theme.secondary[1], theme.secondary[2]);
  pdf.rect(margin, yPosition, contentWidth, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('DISCUSSION QUESTIONS', margin + 3, yPosition + 5.5);
  yPosition += 12;

  studyNotes.discussionQuestions.forEach((question, index) => {
    checkPageBreak(15);

    pdf.setTextColor(theme.primary[0], theme.primary[1], theme.primary[2]);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Q${index + 1}.`, margin + 3, yPosition);

    pdf.setTextColor(60, 60, 60);
    pdf.setFont('helvetica', 'normal');
    const questionLines = pdf.splitTextToSize(question, contentWidth - 15);
    pdf.text(questionLines, margin + 12, yPosition);
    yPosition += questionLines.length * 5 + 6;
  });

  yPosition += 5;
  checkPageBreak(20);

  // Application Points Section
  pdf.setFillColor(theme.secondary[0], theme.secondary[1], theme.secondary[2]);
  pdf.rect(margin, yPosition, contentWidth, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('APPLICATION POINTS', margin + 3, yPosition + 5.5);
  yPosition += 12;

  studyNotes.applicationPoints.forEach((point) => {
    checkPageBreak(12);

    // Checkmark
    pdf.setTextColor(theme.primary[0], theme.primary[1], theme.primary[2]);
    pdf.setFontSize(12);
    pdf.text('✓', margin + 3, yPosition);

    // Point text
    pdf.setTextColor(60, 60, 60);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    const appLines = pdf.splitTextToSize(point, contentWidth - 12);
    pdf.text(appLines, margin + 10, yPosition);
    yPosition += appLines.length * 5 + 5;
  });

  // Add footer to all pages
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addFooter(i);
  }

  // Save the PDF
  const fileName = `${studyNotes.title.replace(/[^a-z0-9]/gi, '_')}_Study_Guide.pdf`;
  pdf.save(fileName);
};
